version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "omermecitoglu"
    allow:
      - dependency-name: "@omer-x/*"
    ignore:
      - dependency-name: "eslint"
        versions: ["9.x"]
